version: '3.8'

services:
  smoky_frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: smoky_frontend-web
    restart: unless-stopped
    
    # Открываем порт для доступа от nginx контейнера
    ports:
      - "8080:80"
    
    environment:
      - NODE_ENV=production
      - TZ=Europe/Moscow
    
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./scripts:/app/scripts:ro
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s