# Docker Compose конфигурация для SmokyApp с внешним nginx
# Настроена для работы за прокси-сервером

version: '3.8'

services:
  # Основное веб-приложение (без внешних портов)
  smokyapp:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: smokyapp-web
    restart: unless-stopped
    
    # Только внутренний порт для проксирования
    expose:
      - "80"
    
    # Переменные окружения
    environment:
      - NODE_ENV=production
      - NGINX_HOST=smokyapp-web
      - NGINX_PORT=80
      - TZ=Europe/Moscow
    
    # Монтирование томов
    volumes:
      # Логи приложения
      - ./logs:/var/log/nginx
      - ./logs:/var/log/smokyapp
      
      # Конфигурация nginx (для горячей перезагрузки)
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      
      # Скрипты обновления
      - ./scripts:/app/scripts:ro
    
    # Ограничения ресурсов
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    
    # Проверка здоровья (внутренняя)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Подключение к внешней сети nginx
    networks:
      - nginx-proxy
      - smokyapp-internal
    
    # Логирование
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  # Сервис для автоматических обновлений
  updater:
    build:
      context: .
      dockerfile: Dockerfile.updater
    container_name: smokyapp-updater
    restart: unless-stopped
    
    environment:
      - REPO_URL=https://github.com/smokyapp/webapp.git
      - BRANCH=main
      - UPDATE_INTERVAL=300
      - WEBHOOK_SECRET=${WEBHOOK_SECRET:-your-secret-key}
    
    volumes:
      # Docker socket для управления контейнерами
      - /var/run/docker.sock:/var/run/docker.sock:ro
      
      # Скрипты обновления
      - ./scripts:/app/scripts
      
      # Логи
      - ./logs:/var/log/smokyapp
    
    # Ограничения ресурсов
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.05'
          memory: 32M
    
    networks:
      - smokyapp-internal
    
    # Зависимости
    depends_on:
      smokyapp:
        condition: service_healthy

# Сетевая конфигурация
networks:
  # Внешняя сеть для подключения к nginx
  nginx-proxy:
    external: true
    name: nginx-proxy
  
  # Внутренняя сеть приложения
  smokyapp-internal:
    driver: bridge
    name: smokyapp-internal

# Именованные тома
volumes:
  nginx-logs:
    driver: local
    name: smokyapp-nginx-logs
  
  app-logs:
    driver: local
    name: smokyapp-logs
